CREATE TABLE acao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    nome_empresa VARCHAR(255) NOT NULL,
    mercado VARCHAR(10) NOT NULL,
    moeda VARCHAR(3) NOT NULL,
    cotacao_atual DECIMAL(19,4),
    data_hora_cotacao TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_acao_ticker UNIQUE (ticker),
    CONSTRAINT ck_acao_mercado CHECK (mercado IN ('BRASIL', 'EUA')),
    CONSTRAINT ck_acao_moeda CHECK (moeda IN ('BRL', 'USD')),
    CONSTRAINT ck_acao_mercado_moeda CHECK (
        (mercado = 'BRASIL' AND moeda = 'BRL') OR
        (mercado = 'EUA' AND moeda = 'USD')
    )
);
