CREATE TABLE carteira_acao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT NOT NULL,
    acao_id BIGINT NOT NULL,
    quantidade DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_carteira_acao UNIQUE (carteira_id, acao_id),
    CONSTRAINT ck_carteira_acao_quantidade CHECK (quantidade >= 0),
    CONSTRAINT fk_carteira_acao_carteira FOREIGN KEY (carteira_id) REFERENCES carteira (id),
    CONSTRAINT fk_carteira_acao_acao FOREIGN KEY (acao_id) REFERENCES acao (id)
);
